# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Update CSVs with current QC ED Stats

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "35 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: America/Toronto
      - name: Run the script
        run: |
          python scripts/scrape_hourly_quebec_ed_stats.py
      - name: Update the weather
        run: |
          python scripts/update_weather.py
      - uses: stefanzweifel/git-auto-commit-action@v4
